# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo02_CalendarWidget日历控件.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(353, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(30, 20, 296, 218))
        # 设置默认选中的日期
        self.calendarWidget.setSelectedDate(QtCore.QDate(2023, 5, 8))
        # 设置最小日期
        self.calendarWidget.setMinimumDate(QtCore.QDate(1752, 9, 14))
        # 设置最大日起
        self.calendarWidget.setMaximumDate(QtCore.QDate(9999, 12, 31))
        # 设置每周第一天为星期一
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Monday)
        # 设置网格线可见
        self.calendarWidget.setGridVisible(True)
        # 设置可以选中单个日期
        self.calendarWidget.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        # 设置水平表头为简短形式，即周一形式
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        # 设置垂直表头为周数
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.ISOWeekNumbers)
        # 设置显示导航栏
        self.calendarWidget.setNavigationBarVisible(True)
        # 设置日期可以编辑
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 353, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # 获取控件中选中的日期
    def getdate(self):
        from PyQt5.QtWidgets import QMessageBox
        # 获取当前选中日期的QDate对象
        date = QtCore.QDate(self.calendarWidget.selectedDate())
        # 获取年份
        year = date.year()
        # 获取月份
        month = date.month()
        # 获取日
        day = date.day()
        QMessageBox.information(MainWindow, "提示", str(year) + "-" + str(month) + "-" + str(day), QMessageBox.Ok)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # 选中日期变化时显示选择的日期
        self.calendarWidget.selectionChanged.connect(self.getdate)


import sys

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()  # 创建窗口对象
    ui = Ui_MainWindow()  # 创建PyQt设计的窗体对象
    ui.setupUi(MainWindow)  # 调用PyQt窗体的方法对窗体对象进行初始化设置
    MainWindow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程
