# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo01_设计不同种类的输入框.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(339, 372)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 61, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 61, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 180, 61, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 250, 61, 31))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 40, 191, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 110, 191, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 180, 191, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 250, 191, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 339, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #为姓名文本框的按Enter信号绑定槽函数，获取用户输入的姓名
        self.lineEdit.returnPressed.connect(self.get_name)
        #为年龄文本框的按Enter信号绑定槽函数，获取用户输入的年龄
        self.lineEdit_2.returnPressed.connect(self.get_age)
        #为班级文本框的按Enter信号绑定槽函数，获取用户输入的班级
        self.lineEdit_3.returnPressed.connect(self.get_class)
        #为分数文本框的按Enter信号绑定槽函数，获取用户输入的分数
        self.lineEdit_4.returnPressed.connect(self.get_score)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "姓名："))
        self.label_2.setText(_translate("MainWindow", "年龄："))
        self.label_3.setText(_translate("MainWindow", "班级："))
        self.label_4.setText(_translate("MainWindow", "分数："))

    #自定义获取姓名的槽函数
    def get_name(self):
        #弹出可以输入字符串的输入框
        name, ok = QtWidgets.QInputDialog.getText(MainWindow, "姓名", "请输入姓名：",QtWidgets.QLineEdit.Normal, "明日科技")
        #判断是否单击了ok按钮
        if ok:
            #获取输入对话框中的字符串，显示在文本框中
            self.lineEdit.setText(name)

    #自定义获取年龄的槽函数
    def get_age(self):
        #弹出可以选择或输入年龄的输入框
        age, ok = QtWidgets.QInputDialog.getInt(MainWindow, "年龄", "请输入年龄：", 20, 1, 100,1)
        #判断是否单击了ok按钮
        if ok:
            #获取输入对话框中的年龄，显示在文本框中
            self.lineEdit_2.setText(str(age))

    #自定义获取班级的槽函数
    def get_class(self):
        #弹出可以选择班级的输入框
        classes, ok = QtWidgets.QInputDialog.getItem(MainWindow, "班级", "请选择班级：", ["一班", "二班", "三班"])
        #判断是否单击了ok按钮
        if ok:
            #获取输入对话框中的班级，显示在文本框中
            self.lineEdit_3.setText(classes)

    #自定义获取分数的槽函数
    def get_score(self):
        #弹出可以选择或输入分数的输入框
        score, ok = QtWidgets.QInputDialog.getDouble(MainWindow, "分数", "请输入分数：", 0.01, 0, 100, 2)
        #判断是否单击了ok按钮
        if ok:
            #获取输入对话框中的分数，显示在文本框中
            self.lineEdit_4.setText(str(score))

import sys

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()  # 创建窗口对象
    ui = Ui_MainWindow()  # 创建PyQt设计的窗体对象
    ui.setupUi(MainWindow)  # 调用PyQt窗体的方法对窗体对象进行初始化设置
    MainWindow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程
