# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo03_滑块QSlider.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #创建水平滑块
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(50, 0, 661, 41))
        #设置最小值为8
        self.horizontalSlider.setMinimum(8)
        #设置最大值为72
        self.horizontalSlider.setMaximum(72)
        #设置通过鼠标拖动时的步长
        self.horizontalSlider.setSingleStep(1)
        #设置通过鼠标点击时的步长
        self.horizontalSlider.setPageStep(1)
        #设置默认值为8
        self.horizontalSlider.setProperty("value", 8)
        #设置滑块为水平滑块
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        #设置在滑块上方显示刻度
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        #设置刻度的间隔
        self.horizontalSlider.setTickInterval(3)
        self.horizontalSlider.setObjectName("horizontalSlider")
        #创建垂直滑块
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(710, 0, 41, 541))
        #设置最小值为8
        self.verticalSlider.setMinimum(8)
        #设置最大值为72
        self.verticalSlider.setMaximum(72)
        #设置滑块为垂直滑块
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        #设置刻度反方向显示
        self.verticalSlider.setInvertedAppearance(True)
        #设置在滑块右侧显示刻度
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksRight)
        #设置刻度的间隔
        self.verticalSlider.setTickInterval(3)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 40, 661, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #为水平滑块绑定valueChanged信号,在值发生改变时触发槽函数
        self.horizontalSlider.valueChanged.connect(self.changeFontSize)

    #定义槽函数,根据滑块的值改变字体大小
    def changeFontSize(self):
        value= self.horizontalSlider.value()
        self.verticalSlider.setValue(value)
        self.label.setFont(QtGui.QFont("微软雅黑",value))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "敢想敢为，注重细节"))

import sys

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()  # 创建窗口对象
    ui = Ui_MainWindow()  # 创建PyQt设计的窗体对象
    ui.setupUi(MainWindow)  # 调用PyQt窗体的方法对窗体对象进行初始化设置
    MainWindow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程