# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo01_弹出五种不同的对话框.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 311)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 100, 101, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 100, 101, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 100, 101, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(390, 100, 101, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(520, 100, 101, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 621, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 关联消息框按钮的方法
        self.pushButton.clicked.connect(self.info)
        # 关联警告框按钮的方法
        self.pushButton_2.clicked.connect(self.warn)
        # 关联提问框按钮的方法
        self.pushButton_3.clicked.connect(self.question)
        # 关联错误框按钮的方法
        self.pushButton_4.clicked.connect(self.critical)
        # 关联关于框按钮的方法
        self.pushButton_5.clicked.connect(self.about)

    # 显示消息对话框
    def info(self):
        #获取对话框的返回值
        select=QMessageBox.information(None, "消息对话框", "这是一个消息对话框！", QMessageBox.Yes | QMessageBox.No)
        #判断是否单击了yes按钮
        if select==QMessageBox.Yes:
            QMessageBox.information(MainWindow,'提醒','您同意了本次请求！')
        else:
            QMessageBox.information(MainWindow,'提醒','您拒绝了本次请求！')

    # 显示警告对话框
    def warn(self):
        QMessageBox.warning(None, "警告对话框", "这是一个警告对话框！", QMessageBox.Ok)

    # 显示提问对话框
    def question(self):
        QMessageBox.question(None, "提问对话框", "这是一个提问对话框！", QMessageBox.Ok)

    # 显示错误对话框
    def critical(self):
        QMessageBox.critical(None, "错误对话框", "这是一个错误对话框！", QMessageBox.Ok)

    # 显示关于对话框
    def about(self):
        QMessageBox.about(None, "关于对话框", "这是一个关于对话框！")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "消息框"))
        self.pushButton_2.setText(_translate("MainWindow", "警告框"))
        self.pushButton_3.setText(_translate("MainWindow", "问答框"))
        self.pushButton_4.setText(_translate("MainWindow", "错误框"))
        self.pushButton_5.setText(_translate("MainWindow", "关于框"))


import sys

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()  # 创建窗口对象
    ui = Ui_MainWindow()  # 创建PyQt设计的窗体对象
    ui.setupUi(MainWindow)  # 调用PyQt窗体的方法对窗体对象进行初始化设置
    MainWindow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程
