# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo02_HorizontalLayout水平布局.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class Demo(QWidget):
    def __init__(self, parent=None):
        super(Demo, self).__init__(parent)
        self.initUI()  # 初始化窗口

    def initUI(self):
        # 创建表单布局
        form = QFormLayout()
        # 创建并设置标签文本
        label1 = QLabel()
        label1.setText("用户名：")
        # 创建输入文本框
        text1 = QLineEdit()
        # 创建并设置标签文本
        label2 = QLabel()
        label2.setText("密码：")
        # 创建输入文本框
        text2 = QLineEdit()
        # 创建登录和取消按钮
        btn1 = QPushButton()
        btn1.setText("登录")
        btn2 = QPushButton()
        btn2.setText("取消")
        # 将上面创建的6个控件分为3行添加到表单布局中
        form.addRow(label1, text1)
        form.addRow(label2, text2)
        form.addRow(btn1)
        form.addRow(btn2)
        # 设置标签总在文本框上方
        form.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        # 设置表单布局
        self.setLayout(form)


import sys

if __name__ == '__main__':
    # 创建登录窗口
    app = QApplication(sys.argv)
    # 创建窗口类对象
    demo = Demo()
    # 显示窗口
    demo.show()
    sys.exit(app.exec_())
