# coding:utf-8
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo02_HorizontalLayout水平布局.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class Demo(QWidget):
    def __init__(self, parent=None):
        super(Demo, self).__init__(parent)
        self.initUI()  # 初始化窗口

    def initUI(self):
        self.setWindowTitle("微信交流")
        # 创建网格布局
        grid = QGridLayout()
        # 创建顶部时间栏
        label1 = QLabel()
        # 显示当前日期时间
        label1.setText(QtCore.QDateTime.currentDateTime().toString("yyyy-MM-dd HH:mm:ss"))
        # 在第一行第一列到第一行第四列添加标签控件，并设置居中对齐
        grid.addWidget(label1, 0, 0, 1, 4, QtCore.Qt.AlignCenter)
        # 创建对方用户头像，昵称及信息，并在网格中嵌套垂直布局显示
        label2 = QLabel()
        label2.setPixmap(QtGui.QPixmap("../image/head1.png"))
        vlayout1 = QVBoxLayout()
        vlayout1.addWidget(QLabel("马云"))
        vlayout1.addWidget(QLabel("老马，在不在，最近还好么？"))
        grid.addWidget(label2, 1, 0, QtCore.Qt.AlignRight)
        grid.addLayout(vlayout1, 1, 1)
        # 创建自己的头型，昵称及信息，并在网格中嵌套垂直布局显示
        label3 = QLabel()
        label3.setPixmap(QtGui.QPixmap("../image/head2.png"))
        vlayout2 = QVBoxLayout()
        vlayout2.addWidget(QLabel("马化腾"))
        vlayout2.addWidget(QLabel("还行吧，最近经济不太景气啊！"))
        grid.addWidget(label3, 2, 3, QtCore.Qt.AlignLeft)
        grid.addLayout(vlayout2, 2, 2)
        # 创建对方用户头像，昵称及第二条信息，并在网格中嵌套垂直布局显示
        label4 = QLabel()
        label4.setPixmap(QtGui.QPixmap("../image/head1.png"))
        label4.resize(24, 24)
        vlayout3 = QVBoxLayout()
        vlayout3.addWidget(QLabel("马云"))
        vlayout3.addWidget(QLabel("嗯，都差不多，一起度过难关吧。。。。。。"))
        grid.addWidget(label4, 3, 0, QtCore.Qt.AlignRight)
        grid.addLayout(vlayout3, 3, 1)
        # 创建输入框，并设置宽度高度，跨列添加到动态网格布局中
        text = QTextEdit()
        text.setFixedWidth(600)
        text.setFixedHeight(80)
        # 在第一行第一列到第一行第四列添加标签控件，并设置居中对齐
        grid.addWidget(text, 4, 0, 1, 4, QtCore.Qt.AlignCenter)
        # 添加发送按钮
        grid.addWidget(QPushButton("发送"), 5, 3, QtCore.Qt.AlignRight)
        # 设置网格布局
        self.setLayout(grid)


import sys

if __name__ == '__main__':
    # 创建登录窗口
    app = QApplication(sys.argv)
    # 创建窗口类对象
    demo = Demo()
    # 显示窗口
    demo.show()
    sys.exit(app.exec_())
