# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grade.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import sys

sys.path.append("../")  # 返回上层路径
from service import service


class Ui_MainWindow(QMainWindow):
    # 构造方法
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setWindowFlags(QtCore.Qt.MSWindowsFixedSizeDialogHint)  # 只显示最小化和关闭按钮
        self.setupUi(self)  # 初始化窗体设置

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(283, 241)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tbGrade = QtWidgets.QTableWidget(self.centralwidget)
        self.tbGrade.setGeometry(QtCore.QRect(0, 0, 281, 161))
        self.tbGrade.setObjectName("tbGrade")
        self.tbGrade.setColumnCount(2)
        self.tbGrade.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbGrade.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbGrade.setHorizontalHeaderItem(1, item)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(148, 170, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.editID = QtWidgets.QLineEdit(self.centralwidget)
        self.editID.setGeometry(QtCore.QRect(77, 170, 61, 20))
        self.editID.setObjectName("editID")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(4, 170, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.editName = QtWidgets.QLineEdit(self.centralwidget)
        self.editName.setGeometry(QtCore.QRect(218, 170, 61, 20))
        self.editName.setObjectName("editName")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(47, 201, 51, 31))
        self.btnAdd.setObjectName("btnAdd")
        self.btnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btnEdit.setGeometry(QtCore.QRect(107, 201, 51, 31))
        self.btnEdit.setObjectName("btnEdit")
        self.btnDel = QtWidgets.QPushButton(self.centralwidget)
        self.btnDel.setGeometry(QtCore.QRect(167, 201, 51, 31))
        self.btnDel.setObjectName("btnDel")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(227, 201, 51, 31))
        self.btnExit.setObjectName("btnExit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btnExit.clicked.connect(MainWindow.close)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.tbGrade.setAlternatingRowColors(True)  # 使表格颜色交错显示
        self.tbGrade.verticalHeader().setVisible(False)  # 隐藏垂直标题
        self.query()  # 窗体加载时显示所有数据
        self.btnAdd.clicked.connect(self.add)  # 绑定添加按钮的单击事件
        self.tbGrade.itemClicked.connect(self.getItem)  # 绑定表格单击事件
        self.btnEdit.clicked.connect(self.edit)  # 绑定修改按钮的单击事件
        self.btnDel.clicked.connect(self.delete)  # 绑定删除按钮的单击事件

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "年级设置"))
        item = self.tbGrade.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "年级编号"))
        item = self.tbGrade.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "年级名称"))
        self.label_3.setText(_translate("MainWindow", "年级名称："))
        self.label_2.setText(_translate("MainWindow", "年级编号："))
        self.btnAdd.setText(_translate("MainWindow", "添加"))
        self.btnEdit.setText(_translate("MainWindow", "修改"))
        self.btnDel.setText(_translate("MainWindow", "删除"))
        self.btnExit.setText(_translate("MainWindow", "退出"))

    # 查询年级信息，并显示在表格中
    def query(self):
        self.tbGrade.setRowCount(0)  # 清空表格
        # 调用服务类的公共方法执行查询语句
        result = service.query("select * from tb_grade")
        row = len(result)  # 获取查询结果的行数
        self.tbGrade.setRowCount(row)  # 设置表格的行数
        self.tbGrade.setColumnCount(2)  # 设置表格的列数
        # 设置表格的标题名称
        self.tbGrade.setHorizontalHeaderLabels(["年级编号", "年级名称"])
        for i in range(row):  # 遍历查询结果
            for j in range(self.tbGrade.columnCount()):  # 遍历列
                # 创建表格中的Item对象
                data = QTableWidgetItem(str(result[i][j]))
                # 设置表格的Item对象
                self.tbGrade.setItem(i, j, data)

    # 获取选中的表格内容
    def getItem(self, item):
        if item.column() == 0:  # 如果单击的是第一列
            self.select = item.text()  # 获取单击的单元格文本
            self.editID.setText(self.select)  # 显示在文本框中

    # 判断要添加的年级编号是否存在
    def getName(self, name):
        result = service.query("select * from tb_grade where gradeName = %s", name)
        return len(result)

    # 添加年级信息
    def add(self):
        gradeID = self.editID.text()  # 获取年级编号
        gradeName = self.editName.text()  # 获取年级名称
        if gradeID != "" and gradeName != "":  # 判断年级编号和年级名称是否为空
            if self.getName(gradeName) > 0:  # 判断年级名称是否存在
                self.editName.setText("")  # 清空年级名称
                QMessageBox.information(None, "提示", "您要添加的年级已经存在，请重新输入！", QMessageBox.Ok)  # 弹出提示信息
            else:
                # 执行添加语句
                result = service.exec("insert into tb_grade(gradeID,gradeName) values(%s,%s)", (gradeID, gradeName))
                if result > 0:  # 判断添加是否成功
                    self.query()  # 调用查询方法，刷新表格
                    QMessageBox.information(None, "提示", "信息添加成功！", QMessageBox.Ok)  # 弹出提示信息
        else:
            QMessageBox.warning(None, "警告", "请输入数据后，再执行相关操作！", QMessageBox.Ok)  # 弹出警告信息

    # 修改年级信息
    def edit(self):
        try:
            if self.select !="":    # 判断是否选中表格内容
                gradeName = self.editName.text()  # 获取年级名称
                if gradeName != "":  # 判断年级名称是否为空
                    if self.getName(gradeName) > 0:  # 判断年级名称是否存在
                        self.editName.setText("")  # 清空年级名称
                        QMessageBox.information(None, "提示", "您要修改的年级已经存在，请重新输入！", QMessageBox.Ok)  # 弹出提示信息
                    else:
                        result=service.exec("update tb_grade set gradeName=%s where gradeID=%s",(gradeName,self.select))
                        if result>0:    # 判断修改是否成功
                            self.query() # 调用查询方法，刷新表格
                            QMessageBox.information(None, "提示", "信息修改成功！", QMessageBox.Ok)  # 弹出提示信息
        except:
            QMessageBox.warning(None, "警告", "请先选择要修改的数据！", QMessageBox.Ok)

    # 删除年级信息
    def delete(self):
        try:
            if self.select !="":    # 判断是否选中表格内容
                result=service.exec("delete from tb_grade where gradeID=%s",(self.select,)) # 执行删除语句
                if result>0:    # 判断删除是否成功
                    self.query() # 调用查询方法，刷新表格
                result=service.exec("delete from tb_student where gradeID=%s",(self.select,))   # 删除学生信息
                if result>0:    # 判断删除是否成功
                    self.query() # 调用查询方法，刷新表格
                QMessageBox.information(None, '提示', '信息删除成功！', QMessageBox.Ok)
        except:
            QMessageBox.warning(None, '警告', '请先选择要删除的数据！', QMessageBox.Ok)


