# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo02_HorizontalLayout水平布局.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class Demo(QWidget):
    def __init__(self, parent=None):
        super(Demo, self).__init__(parent)
        self.initUI()  # 初始化窗口

    def initUI(self):
        # 创建网格布局
        grid = QGridLayout()
        # 创建并设置标签文本
        label1 = QLabel()
        label1.setText("用户名：")
        # 创建输入文本框
        text1 = QLineEdit()
        # 创建并设置标签文本
        label2 = QLabel()
        label2.setText("密码：")
        # 创建输入文本框
        text2 = QLineEdit()
        # 创建登录和取消按钮
        btn1 = QPushButton()
        btn1.setText("登录")
        btn2 = QPushButton()
        btn2.setText("取消")
        # 在第一行第一列添加标签控件，并设置左对齐
        grid.addWidget(label1, 0, 0, QtCore.Qt.AlignLeft)
        # 在第一行第二列添加输入文本框控件，并设置左对齐
        grid.addWidget(text1, 0, 1, QtCore.Qt.AlignLeft)
        # 在第二行第一列添加标签控件，并设置左对齐
        grid.addWidget(label2, 1, 0, QtCore.Qt.AlignLeft)
        # 在第二行第二列添加输入文本框控件，并设置左对齐
        grid.addWidget(text2, 1, 1, QtCore.Qt.AlignLeft)
        # 在第三行第一列添加按钮控件，并设置居中对齐
        grid.addWidget(btn1, 2, 0, QtCore.Qt.AlignCenter)
        # 在第一行第二列添加按钮控件，并设置左对齐
        grid.addWidget(btn2, 2, 1, QtCore.Qt.AlignCenter)
        # 设置网格布局
        self.setLayout(grid)


import sys

if __name__ == '__main__':
    # 创建登录窗口
    app = QApplication(sys.argv)
    # 创建窗口类对象
    demo = Demo()
    # 显示窗口
    demo.show()
    sys.exit(app.exec_())
