# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo02_HorizontalLayout水平布局.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class Demo(QWidget):
    def __init__(self, parent=None):
        super(Demo, self).__init__(parent)
        self.initUI()  # 初始化窗口

    def initUI(self):
        self.setWindowTitle("QQ 登录窗口")
        # 创建网格布局
        grid = QGridLayout()
        # 创建顶部图片
        label1 = QLabel()
        label1.setPixmap(QtGui.QPixmap('../image/top.png'))
        # 创建并设置用户名标签文本
        label2 = QLabel()
        label2.setPixmap(QtGui.QPixmap('../image/qq1.png'))
        # 创建用户名输入文本框
        text1 = QLineEdit()
        # 创建并设置标签文本
        label3 = QLabel()
        label3.setPixmap(QtGui.QPixmap('../image/qq2.png'))
        # 创建输入文本框
        text2 = QLineEdit()
        # 创建“安全登录”按钮
        btn1 = QPushButton()
        btn1.setText("安全登录")
        # 在第一行第一列到第三行第四列添加标签控件，并设置居中对齐
        grid.addWidget(label1, 0, 0, 3, 4, QtCore.Qt.AlignCenter)
        # 在第四行第二列添加标签控件，并设置右对齐
        grid.addWidget(label2, 3, 1, QtCore.Qt.AlignRight)
        # 在第四行第三列添加输入文本框控件，并设置左对齐
        grid.addWidget(text1, 3, 2, QtCore.Qt.AlignLeft)
        # 在第五行第二列添加标签控件，并设置右对齐
        grid.addWidget(label3, 4, 1, QtCore.Qt.AlignRight)
        # 在第五行第三列添加输入文本框控件，并设置左对齐
        grid.addWidget(text2, 4, 2, QtCore.Qt.AlignLeft)
        # 在第六行第二列到第三列添加按钮控件，并设置居中对齐
        grid.addWidget(btn1, 5, 1, 1, 2, QtCore.Qt.AlignCenter)
        # 设置网格布局
        self.setLayout(grid)


import sys

if __name__ == '__main__':
    # 创建登录窗口
    app = QApplication(sys.argv)
    # 创建窗口类对象
    demo = Demo()
    # 显示窗口
    demo.show()
    sys.exit(app.exec_())
